// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uovheptdbwoksgkeuxnk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVvdmhlcHRkYndva3Nna2V1eG5rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3Mzc0NDAsImV4cCI6MjA2ODMxMzQ0MH0.653SoVQTdsh-8efnUhJBINJW3xVee0PvL-5ZIHbpg4o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});